# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'WebRTC_Learn' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for WebRTC_Learn

  pod 'SocketRocket', '~> 0.5.1'
  pod 'GoogleWebRTC', '~> 1.1.22075'

end
